management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    hikari:
      maximum-pool-size: 90
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: P0stgr3s!@#%123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
