CREATE TABLE LOCATION (ID SERIAL PRIMARY KEY, LOCATION_ID VARCHAR(63) UNIQUE, DESCRIPTION VARCHAR(255), CREATED_TIME TIMESTAMP,
 LAST_MODIFIED_TIME TIMESTAMP);

CREATE TABLE RESERVATION (ID SERIAL PRIMARY KEY, RESERVATION_ID VARCHAR(255) UNIQUE, FIRST_NAME VARCHAR(63),
LAST_NAME VARCHAR(63), EMAIL VARCHAR(255), ARRIVAL DATE, DEPARTURE DATE, STATUS VARCHAR(63), LOCATION_ID VARCHAR(63)
REFERENCES LOCATION(LOCATION_ID), CREATED_TIME TIMESTAMP, LAST_MODIFIED_TIME TIMESTAMP);

CREATE TABLE AVAILABILITY (ID SERIAL PRIMARY KEY, LOCATION_ID VARCHAR(63) REFERENCES LOCATION(LOCATION_ID),
RESERVATION_DATE DATE, RESERVATION_ID VARCHAR(255) REFERENCES RESERVATION(RESERVATION_ID), CREATED_TIME TIMESTAMP,
 LAST_MODIFIED_TIME TIMESTAMP, UNIQUE (LOCATION_ID, RESERVATION_DATE));

INSERT INTO location("location_id", "description", "created_time", "last_modified_time")
VALUES ('ISL_VOLC_PO', 'Pacific Ocean Volcano Island', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
